version: '3.8'
services:
  web:
    container_name: trip.ai-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MONGODB_URI: ${MONGODB_URI}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

    # Uncomment the following lines if your application depends on MongoDB running as part of your Docker setup
    # depends_on:
    #   - mongo
# Uncomment this section if you want to include a MongoDB service in your Docker environment
#  mongo:
#    container_name: mongo
#    image: mongo:latest
#    ports:
#      - '27017:27017'
#    volumes:
#      - mongo-data:/data/db
#    healthcheck:
#      test: ['CMD', 'mongo', '--eval', "db.runCommand('ping').ok"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

# Uncomment if using the MongoDB service
#volumes:
#  mongo-data:
