name: CI Workflow

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --verbose

      - name: Run Linter
        run: npm run lint

      # Optionally wait for services to be fully up and running
      # This step would require a script that checks the readiness of your services
      # - name: Wait for Services to be Ready
      #   run: ./scripts/wait-for-services.sh

      - name: Build Project
        run: npm run build
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: Run Tests
        run: npm run test
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - uses: actions/checkout@v3

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        run: |
          docker login tripairegistry.azurecr.io -u ${{ secrets.AZURE_REGISTRY_USERNAME }} -p ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      # Build and push Docker image with a meaningful tag
      - name: Build and push Docker image
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
          TIMESTAMP=$(date -u +"%Y%m%dT%H%M%SZ")
          IMAGE_TAG=${BRANCH_NAME}-${TIMESTAMP}
          docker build -t tripairegistry.azurecr.io/tripai:$IMAGE_TAG .
          docker push tripairegistry.azurecr.io/tripai:$IMAGE_TAG
        env:
          GITHUB_REF: ${{ github.ref }}
