name: CI Workflow

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --verbose

      - name: Run Linter
        run: npm run lint

      # Assuming you want to start your application and dependencies before building and testing
      - name: Start Docker Compose Services
        run: docker-compose up -d
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      # Optionally wait for services to be fully up and running
      # This step would require a script that checks the readiness of your services
      # - name: Wait for Services to be Ready
      #   run: ./scripts/wait-for-services.sh

      - name: Build Project
        run: npm run build
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: Run Tests
        run: npm run test
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      # Stop and remove Docker Compose services after tests or builds
      - name: Docker Compose Down
        run: docker-compose down
